package com.sappenin.fastpay.core;

/**
 * Error codes returned by a Fastpay Authority server.
 */
public enum FastpayErrorCode {
  INVALID_SIGNATURE,
  UNKNOWN_SIGNER,
  CERTIFICATE_REQUIRES_QUORUM,
  INCORRECT_TRANSFER_AMOUNT,
  UNEXPECTED_SEQUENCE_NUMBER,
  INSUFFICIENT_FUNDING,
  PREVIOUS_TRANSFER_MUST_BE_CONFIRMED_FIRST,
  ERROR_WHILE_PROCESSING_TRANSFERORDER,
  ERROR_WHILE_REQUESTING_CERTIFICATE,
  MISSING_EALIER_CONFIRMATIONS,
  UNEXPECTED_TRANSACTION_INDEX,
  CERTIFICATE_NOT_FOUND,
  UNKNOWN_SENDER_ACCOUNT,
  CERTIFICATE_AUTHORITY_REUSE,
  INVALID_SEQUENCE_NUMBER,
  SEQUENCE_OVERFLOW,
  SEQUENCE_UNDERFLOW,
  AMOUNT_OVERFLOW,
  AMOUNT_UNDERFLOW,
  BALANCE_OVERFLOW,
  BALANCE_UNDERFLOW,
  WRONG_SHARD,
  INVALID_CROSS_SHARD_UPDATE,
  INVALID_DECODING,
  UNEXPECTED_MESSAGE,
  CLIENT_IO_ERROR;
}
